[build-system]
build-backend = "hatchling.build"

requires = [ "hatch-vcs>=0.3", "hatchling>=1.24.2" ]

[project]
name = "epicsarchiver-mgmt"
description = "Tool for doing archiver mgmt operations"
readme = "README.md"
keywords = [  ]
license = "MIT"
authors = [ { name = "skybrewer", email = "sky.brewer@ess.eu" } ]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = [ "version" ]
dependencies = [ "click>=8", "python-dateutil", "pytz", "requests>=2", "rich>=13" ]

urls.Documentation = "https://gitlab.esss.lu.se/ics-software/archiver-appliance/epicsarchiver-mgmt#readme"
urls.Issues = "https://gitlab.esss.lu.se/ics-software/archiver-appliance/epicsarchiver-mgmt/issues"
urls.Source = "https://gitlab.esss.lu.se/ics-software/archiver-appliance/epicsarchiver-mgmt"
scripts.arch-mgmt = "epicsarchiver_mgmt.command:cli"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
git_describe_command = [ "git", "describe", "--dirty", "--tags", "--long" ]

[tool.hatch.build.hooks.vcs]
version-file = "src/epicsarchiver_mgmt/_version.py"

[tool.hatch.envs.default.env-vars]
UV_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"
PIP_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"

[tool.hatch.envs.hatch-test.env-vars]
UV_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"
PIP_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"

[tool.hatch.envs.default.scripts]
type-check = "hatch run types:check"

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/epicsarchiver_mgmt tests}"

[tool.hatch.envs.types]
extra-dependencies = [
  "responses",
  "mypy>=1.0.0",
  "pytest",
  "pytest-mock",
  "types-requests",
]

[tool.hatch.envs.hatch-test]
extra-dependencies = [ "responses", "pytest-mock", "pytest" ]

[tool.hatch.envs.docs]
extra-dependencies = [
  "astroid==3.3.11",
  "sphinx",
  "sphinx-copybutton>=0.5.1",
  "sphinx-click",
  "sphinx-autobuild",
  "sphinx-autoapi>=3.6.0",
  "sphinx_rtd_theme",
  "myst-parser",
]

[tool.hatch.envs.docs.scripts]
build = [ "make -C docs html" ]
check = [ 'make -C docs html SPHINXOPTS="-W --keep-going"' ]
live = [ "sphinx-autobuild docs/source docs/build/html" ]
clean = [ "make -C docs clean html" ]

[tool.ruff]
line-length = 120
preview = true

format.docstring-code-line-length = 80
format.docstring-code-format = true
lint.select = [ "ALL" ]
lint.ignore = [
  "COM812", # ignore checking for trailing comma, let formatter handle it
  "CPY001", # ignore copyright header checking (not needed for internal projects)
  "ISC001", # Conflicts with the formatter
]
lint.per-file-ignores."docs/**/*" = [
  "INP001", # docs/ is not a Python package
]
lint.per-file-ignores."src/epicsarchiver_mgmt/command.py" = [
  "BLE001", # ignore "bare except" in command.py as it is a command line tool
]
lint.per-file-ignores."tests/**/*" = [
  "D",       # Don't enforce docstrings in tests
  "PLR2004", # allow magic constants in tests
  "S101",    # allow asserts in tests
]
lint.flake8-pytest-style.fixture-parentheses = false
lint.flake8-pytest-style.mark-parentheses = false
lint.flake8-tidy-imports.ban-relative-imports = "all"
lint.isort.known-first-party = [ "epicsarchiver_mgmt" ]
# Use Google-style docstrings.
lint.pydocstyle.convention = "google"
lint.pylint.max-args = 10
lint.pylint.max-positional-args = 10

[tool.coverage.run]
source_pkgs = [ "epicsarchiver_mgmt", "tests" ]
branch = true
parallel = true
omit = [ "src/epicsarchiver_mgmt/__about__.py" ]

[tool.coverage.paths]
epicsarchiver-mgmt = [
  "src/epicsarchiver_mgmt",
]
tests = [ "tests" ]

[tool.coverage.report]
exclude_lines = [ "no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:" ]

[tool.mypy]
strict = true
