[build-system]
build-backend = "hatchling.build"

requires = [ "hatchling" ]

[project]
name = "archiver-mgmt-operations"
description = "Tool for doing archiver mgmt operations"
readme = "README.md"
keywords = [  ]
license = "MIT"
authors = [ { name = "skybrewer", email = "sky.brewer@ess.eu" } ]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = [ "version" ]
dependencies = [ "click>=8", "py-epicsarchiver>=0.16", "rich>=13" ]

urls.Documentation = "https://github.com/skybrewer/archiver-mgmt-operations#readme"
urls.Issues = "https://github.com/skybrewer/archiver-mgmt-operations/issues"
urls.Source = "https://github.com/skybrewer/archiver-mgmt-operations"
scripts.archapplmgmt = "archiver_mgmt_operations.command:cli"

[tool.hatch.version]
path = "src/archiver_mgmt_operations/__about__.py"

[tool.hatch.envs.default.env-vars]
UV_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"
PIP_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"

[tool.hatch.envs.hatch-test.env-vars]
UV_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"
PIP_EXTRA_INDEX_URL = "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"

[tool.hatch.envs.default.scripts]
type-check = "hatch run types:check"

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/archiver_mgmt_operations tests}"

[tool.hatch.envs.types]
extra-dependencies = [
  "responses",
  "mypy>=1.0.0",
  "pytest",
  "pytest-mock",
  "types-requests",
]

[tool.hatch.envs.hatch-test]
extra-dependencies = [ "responses", "pytest-mock", "pytest" ]

[tool.ruff]
line-length = 120
preview = true

format.docstring-code-line-length = 80
format.docstring-code-format = true
lint.select = [ "ALL" ]
lint.ignore = [
  "COM812", # ignore checking for trailing comma, let formatter handle it
  "CPY001", # ignore copyright header checking (not needed for internal projects)
  "ISC001", # Conflicts with the formatter
]
lint.per-file-ignores."tests/**/*" = [
  "D",       # Don't enforce docstrings in tests
  "PLR2004", # allow magic constants in tests
  "S101",    # allow asserts in tests
]
lint.flake8-pytest-style.fixture-parentheses = false
lint.flake8-pytest-style.mark-parentheses = false
lint.flake8-tidy-imports.ban-relative-imports = "all"
lint.isort.known-first-party = [ "archiver_mgmt_operations" ]
# Use Google-style docstrings.
lint.pydocstyle.convention = "google"
lint.pylint.max-args = 10
lint.pylint.max-positional-args = 10

[tool.coverage.run]
source_pkgs = [ "archiver_mgmt_operations", "tests" ]
branch = true
parallel = true
omit = [ "src/archiver_mgmt_operations/__about__.py" ]

[tool.coverage.paths]
archiver_mgmt_operations = [
  "src/archiver_mgmt_operations",
  "*/archiver-mgmt-operations/src/archiver_mgmt_operations",
]
tests = [ "tests", "*/archiver-mgmt-operations/tests" ]

[tool.coverage.report]
exclude_lines = [ "no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:" ]

[tool.mypy]
strict = true
